name: EPG

# Controls when the action will run.
on:
  push:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Main Script
        env:
          EPG_URL: ${{ secrets.EPG_URL }}
        run: |
          pip install -r requirements.txt
          python3 main.py

      - name: Add changes
        run: |
          git add -A
          ls -la

      - name: Commit and Push
        run: |
          git commit -m "EPG Updated"
          git push
